sudo: required
dist: xenial
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install make curl zip unzip check -qq
script:
- make
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: Ut1v1bobQDAd5X4AFhmXglouOYlw8hnwuO2AJsXfLsqd2a9IS60GA328xzsd3Bl8qJvsgXS+EtSyc/Jndv9+g3i7IyjGx0cLKXAFldshuO93WsZdklY3ChJTHvGJubElp8m1EfELVCqqPbuSLU2TzFbVDn7yUOso+IVjwlSSpj0HqKdccu+15FBa64D2efLX7jhOMm7UUWMaIeR0dabpDplIaYn2suIrYSMqyJYOR8J6G0zD7UHLL0m/pl7OpPFBi7l0kZ94Le84Q3PuNx0Ld6bnYgCDtbhAKoA3UIIff+E8QsOxbi41POnjbLDky1eROEuVkadTEdmjiwBjUNQ1AnHpink4X0eTY0ct0gp/AAXad3YhvqcEg5VPMxzWZZjvffxkMqnzwXVE1IE0KIPcxGgukU+KkZzgl7OE2XUWhOgtJDX96Xpv1x6YHFbig/W7yi9h8BhMBA2fSzXCBRWVQeKliYbgfwXR/RXKc7xx6gjIQRK5t/4cbL8hrdzD7S7wjLMBiJu9+CyHPKE4wTXO1Zbk8pKzJe4BFUXxROlYLXE+tBA7HS1y+zO8/f4nAT4F3504jyxvOXUwpAMdVjWk2PNwDvvsR3UUpIfreV0zPyP3TrsnNjIUBA2tjVNK1DQ0GLhDRJneBkdcBiK678clID89prHzoiTCQPr7ZL7lyAQ=
  file: VoidMusl.zip
  on:
    repo: am11/VoidMuslWSL
    tags: true
    all_branches: true
  skip_cleanup: true
